from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, Iterator, List, Optional, Self, Set, Tuple, Union

from oraqle.compiler.graphviz import DotFile


def select_stack_index(stack_occupied: List[bool]) -> int:
    """Selects a free index in the stack and occupies it.

    Returns:
        The first free index in `stack_occupied`.
    """
    for index, occupied in enumerate(stack_occupied):
        if not occupied:
            stack_occupied[index] = True
            return index

    index = len(stack_occupied)
    stack_occupied.append(True)
    return index


class Node[Operand: "Node"](ABC):

    @property
    @abstractmethod
    def _node_label(self) -> str:
        pass

    # TODO: This property should be removed if we do not provide a default hash implementation.
    @property
    @abstractmethod
    def _hash_name(self) -> str:
        pass

    @property
    def _overriden_graphviz_attributes(self) -> dict:
        return {"style": "rounded,filled", "fillcolor": "cornsilk"}
    
    def __init__(self) -> None:
        # TODO: We should probably make separate methods to clear individual caches
        self._to_graph_cache: Optional[int] = None
        self._instruction_cache: Optional[int] = None
        self._parent_count_cache: Optional[int] = None

        self._hash = None

        self._party = None
        self._plaintext = False
        self._parent_count = 0

    @abstractmethod
    def apply_function_to_operands(self, function: Callable[[Operand], None]):
        """Applies function to all operands of this node."""

    @abstractmethod
    def replace_operands_using_function(self, function: Callable[[Operand], Operand]):
        """Replaces each operand of this node with the node generated by calling function on said operand."""

    def clear_cache(self, already_cleared: Set[int]):
        """Clears any cached values of the node and any of its operands.
        
        Implementers must call super().clear_cache()."""
        # FIXME: The cache should not be cleared twice for the same node, but there is no way to check this.
        if id(self) not in already_cleared:
            self.apply_function_to_operands(lambda operand: operand.clear_cache(already_cleared))

        self._to_graph_cache: Optional[int] = None
        self._instruction_cache: Optional[int] = None
        self._parent_count_cache: Optional[int] = None

        self._hash = None

        already_cleared.add(id(self))

    def to_graph(self, graph_builder: DotFile) -> int:
        """Adds this node to the graph as well as its edges.

        Returns:
            The identifier of this `Node` in the `DotFile`.
        """
        if self._to_graph_cache is None:
            attributes = {"shape": "box"}
            attributes.update(self._overriden_graphviz_attributes)

            self._to_graph_cache = graph_builder.add_node(
                label=self._node_label,
                **attributes,
            )

            # FIXME: This does not take multiplicity into account; add option to apply_function_to_operands to take multiplicity into account
            self.apply_function_to_operands(lambda operand: graph_builder.add_link(operand.to_graph(graph_builder), self._to_graph_cache))  # type: ignore

        return self._to_graph_cache

    @abstractmethod
    def __hash__(self) -> int:
        raise NotImplementedError(
            "The abstract class does not provide a default implementation of __hash__"
        )

    # TODO: We can add a strategy to this method, e.g. to exhaustively check equivalence.
    @abstractmethod
    def is_equivalent(self, other: "Node") -> bool:
        """Checks whether two nodes are semantically equivalent.

        This method will always return `False` if they are not.
        This method will maybe return True if they are indeed equivalent.
        In other words, this method may produce false negatives, but it will never produce false positives.
        """

    # TODO: Rework CSE. In an arithmetic circuit, it should only return arithmetic nodes.
    def eliminate_common_subexpressions(self, terms: Dict[int, "Node"]) -> "Node":
        """Eliminates duplicate subexpressions that are equivalent (as defined by a node's `__eq__` and `__hash__` method).

        Returns:
            A `Node` that must replace the previous expression.
        """
        # TODO: What if we try breadth-first search? It will be more expensive but it will save the lowest depth solution first.
        # FIXME: Handle conflicts (duplicate hashes) using a list instead of a single node.
        # TODO: For performance reasons, maybe we should only save terms of a certain maximum depth.
        h = hash(self)
        if h in terms and self.is_equivalent(terms[h]):
            return terms[h]

        self.replace_operands_using_function(
            lambda operand: operand.eliminate_common_subexpressions(terms)  # type: ignore
        )

        terms[h] = self
        return self

    def count_parents(self):
        """Counts the total number of nodes in this subcircuit."""
        self._parent_count += 1

        if self._parent_count_cache is None:
            self._parent_count_cache = True
            self.apply_function_to_operands(lambda operand: operand.count_parents())

    def reset_parent_count(self):
        """Resets the cached number of nodes in this subcircuit to 0."""
        self._parent_count = 0
        self.apply_function_to_operands(lambda operand: operand.reset_parent_count())


class UnoverloadedWrapper[N: Node]:
    """The `UnoverloadedWrapper` class wraps a `Node` such that hash(.) and x == y work as expected.
    
    !!! note
        The equality operator perform semantic equality!
    """

    def __init__(self, node: N) -> None:
        """Wrap `Node`."""
        self.node = node

    def __hash__(self) -> int:
        return hash(self.node)

    def __eq__(self, other) -> bool:
        if not isinstance(other, UnoverloadedWrapper):
            return False

        if hash(self) != hash(other):
            return False

        return self.node.is_equivalent(other.node)
